---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
    # checks that we've logged into docker hub
      - name: Login to Docker Hub
        uses: docker/loogin-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Checks that we've checkedout  
      - name: Checkout
        uses: actions/checkout@v2
    # Runs our unit tests
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
    # Runs our lint testing (formatting, syntx etc)
      - name: Lint
        run: docker-compose run --rm app she -c "flaked"